version: '3.8'

services:
  # MongoDB Database
  mongo:
    image: mongo:7.0
    container_name: servicedesk-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: servicedeskai
    volumes:
      - mongo-data:/data/db
    networks:
      - servicedesk-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: servicedesk-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/servicedeskai
      - JWT_SECRET=your-secret-key-change-in-production-2024
      - JWT_EXPIRE=7d
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongo
    networks:
      - servicedesk-network
    command: npm run dev

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: servicedesk-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_SOCKET_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - servicedesk-network
    stdin_open: true
    tty: true

networks:
  servicedesk-network:
    driver: bridge

volumes:
  mongo-data:
